import { auth } from "@/auth";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: see if I can get user info from server instead of client. Making too many calls to middleware
  // const session = await auth();
  return (
    // <SessionProvider session={session}>
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-background")}>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Toaster closeButton richColors position="top-center" />
          {children}
        </ThemeProvider>
      </body>
    </html>
    // </SessionProvider>
  );
}
